# Coverting files format ".mat" to ".csv"

Step 1: Importing Necessary Libraries

In [10]:
import scipy.io
import pandas as pd
import numpy as np

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNX86, Created on: Thu Feb 19 17:38:58 2009', '__version__': '1.0', '__globals__': [], 'trnid': array([[6765, 6755, 6768, ..., 8026, 8036, 8041]], dtype=uint16), 'valid': array([[6773, 6767, 6739, ..., 8028, 8008, 8030]], dtype=uint16), 'tstid': array([[6734, 6735, 6737, ..., 8044, 8045, 8047]], dtype=uint16)}


Step 2: Load the `.mat` File

In [ ]:

mat = scipy.io.loadmat(r'C:\Users\Aditya\OneDrive\Desktop\Flower\data\setid.mat')

print(mat)



In [11]:
print(mat.keys())

dict_keys(['__header__', '__version__', '__globals__', 'trnid', 'valid', 'tstid'])


Step 3: Save the data in a .csv file.

In [12]:
for key in mat.keys():

    if not key.startswith('__'):
        print(mat[key])
        df = pd.DataFrame()
        df[key]=np.array(mat[key]).flatten()
        print(df)
        df.to_csv(f'C:\\Users\\Aditya\\OneDrive\\Desktop\\Flower\\data\\{key}.csv', index=False,header=True)
        print(f"Saved {key}.csv")

[[6765 6755 6768 ... 8026 8036 8041]]
      trnid
0      6765
1      6755
2      6768
3      6736
4      6744
...     ...
1015   8004
1016   8013
1017   8026
1018   8036
1019   8041

[1020 rows x 1 columns]
Saved trnid.csv
[[6773 6767 6739 ... 8028 8008 8030]]
      valid
0      6773
1      6767
2      6739
3      6749
4      6763
...     ...
1015   8046
1016   8009
1017   8028
1018   8008
1019   8030

[1020 rows x 1 columns]
Saved valid.csv
[[6734 6735 6737 ... 8044 8045 8047]]
      tstid
0      6734
1      6735
2      6737
3      6742
4      6743
...     ...
6144   8040
6145   8043
6146   8044
6147   8045
6148   8047

[6149 rows x 1 columns]
Saved tstid.csv
